echo kill $(sudo netstat -anp | awk '/ LISTEN / {if($4 ~ ":58001$") { gsub("/.*","",$7); print $7; exit } }')
echo kill $(sudo netstat -anp | awk '/ LISTEN / {if($4 ~ ":58002$") { gsub("/.*","",$7); print $7; exit } }')
echo kill $(sudo netstat -anp | awk '/ LISTEN / {if($4 ~ ":58003$") { gsub("/.*","",$7); print $7; exit } }')
echo kill $(sudo netstat -anp | awk '/ LISTEN / {if($4 ~ ":58004$") { gsub("/.*","",$7); print $7; exit } }')
echo kill $(sudo netstat -anp | awk '/ LISTEN / {if($4 ~ ":58005$") { gsub("/.*","",$7); print $7; exit } }')
echo kill $(sudo netstat -anp | awk '/ LISTEN / {if($4 ~ ":58006$") { gsub("/.*","",$7); print $7; exit } }')